/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgAgenda_Virtual;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Carlos
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        timer.start(); 
        timerfade.start();
        H.ConectarBD();
        frmLogin.this.setAlwaysOnTop(false);
        this.getRootPane().setDefaultButton(btnAceptar);
        txtUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        lblcontra1 = new javax.swing.JLabel();
        lblcontra = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        NuevoUsu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 PM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 5, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Prototype Systems");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 15, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("v2.0");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 710, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Agenda Virtual");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 710, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 300, 40));

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 300, 40));

        lblcontra1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcontra1.setForeground(new java.awt.Color(255, 255, 255));
        lblcontra1.setText("Usuario:");
        getContentPane().add(lblcontra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        lblcontra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcontra.setForeground(new java.awt.Color(255, 255, 255));
        lblcontra.setText("Contraseña:");
        getContentPane().add(lblcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        btnAceptar1.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar1.setText("Recuperar Contraseña");
        btnAceptar1.setBorder(null);
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 150, 30));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Ingresar");
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 130, 40));

        NuevoUsu.setBackground(new java.awt.Color(255, 255, 255));
        NuevoUsu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NuevoUsu.setForeground(new java.awt.Color(255, 255, 255));
        NuevoUsu.setText(" ¿Sin Usuario? Click aca..");
        NuevoUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        NuevoUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoUsuMouseClicked(evt);
            }
        });
        getContentPane().add(NuevoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 180, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgAgenda_Virtual/Images/3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 290, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgAgenda_Virtual/Images/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    public float trans2 = 1.0f;
    public ResultSet rs = null;
    DefaultListModel model;
    public static int usu = 0;
    public static String usuario = "";
    
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.setAlwaysOnTop(false);
        try{
        String Usu, Con;
        usuario = txtUsuario.getText();
        int Usuario = 0;
        Usu = H.encriptar(txtUsuario.getText());
        Con = H.encriptar(String.valueOf(txtContraseña.getPassword()));
        rs = H.Buscar("SELECT cod_usu, usu_usu FROM Usuarios WHERE usu_usu = '" + Usu +"' AND contra_usu = '"+ Con +"'");
        while(rs.next()){
            Usuario = rs.getInt(1);
            H.Usu = H.desencriptar(rs.getString(2));
        }   
        if(Usuario > 0){
            frmAgenda.ver = 1;
            H.Usuario = Usuario;
            while(trans2 > 0.1f){
                trans2 -= 0.000001f;
                this.setOpacity(trans2);
            }
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");
        }
        }        
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    public static int nuvusu = 0;
    private void NuevoUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoUsuMouseClicked
        this.setAlwaysOnTop(false);
        if(nuvusu == 0){
        frmNuevoUsu NU = new frmNuevoUsu();
        NU.show();
        NU.setAlwaysOnTop(true);
        nuvusu = 1;
        }
    }//GEN-LAST:event_NuevoUsuMouseClicked

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        frmRecuperarContraseña rc = new frmRecuperarContraseña(this, rootPaneCheckingEnabled);
        rc.setVisible(true);
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    Timer timerfade = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 0.0f;
        while(f < 1.0f){
            frmLogin.this.setOpacity(f);
            f += 0.00001f;            
        }
        timerfade.stop();
     } 
});
    
    
    Timer timer = new Timer (1000, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
      Date fecha = new Date();
      SimpleDateFormat hora = new SimpleDateFormat("hh:mm a");         
      lblHora.setText(hora.format(fecha));      
     } 
});
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NuevoUsu;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblcontra;
    private javax.swing.JLabel lblcontra1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
