/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgAgenda_Virtual;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;



/**
 *
 * @author Carlos
 */
public class frmModificarActividades extends javax.swing.JDialog {

    /**
     * Creates new form frmModificarActividad
     */
    public frmModificarActividades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cmbtipact();
        getAct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMinutos = new javax.swing.JComboBox();
        cmbHoras = new javax.swing.JComboBox();
        txtLugar = new javax.swing.JTextField();
        lblTitulo3 = new javax.swing.JLabel();
        txtNomAct = new javax.swing.JTextField();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblTitulo5 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        cmbAño = new javax.swing.JComboBox();
        cmbMes = new javax.swing.JComboBox();
        cmbtipact = new javax.swing.JComboBox();
        lblTitulo6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        mbnAgregarActs = new javax.swing.JMenuBar(){
            public void paintComponent(Graphics g){
                g.drawImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pkgAgenda_Virtual/Images/Toolbar.png")),0,0,this);
            }
        };
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMinutos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbMinutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(cmbMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 237, 99, -1));

        cmbHoras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbHoras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(cmbHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 237, 85, -1));

        txtLugar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugarKeyTyped(evt);
            }
        });
        getContentPane().add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 283, 282, -1));

        lblTitulo3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo3.setText("Lugar Actividad:");
        getContentPane().add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 286, -1, -1));

        txtNomAct.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomActKeyTyped(evt);
            }
        });
        getContentPane().add(txtNomAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 11, 286, -1));

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo2.setText("Descripcion Actividad:");
        getContentPane().add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo1.setText("Nombre Actividad:");
        getContentPane().add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 14, -1, -1));

        cmbDia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 191, 60, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 57, -1, -1));

        lblTitulo5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo5.setText("Hora Actividad:");
        getContentPane().add(lblTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 240, -1, -1));

        lblTitulo4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo4.setText("Fecha Actividad:");
        getContentPane().add(lblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 194, -1, -1));

        cmbAño.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015" }));
        getContentPane().add(cmbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 191, 90, -1));

        cmbMes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 191, 60, -1));

        cmbtipact.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbtipact.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estudios" }));
        getContentPane().add(cmbtipact, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 329, 282, -1));

        lblTitulo6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo6.setText("Tipo de Actividad:");
        getContentPane().add(lblTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 332, -1, -1));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 11, 111, 36));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 65, 111, 36));

        mbnAgregarActs.setBorder(null);
        mbnAgregarActs.setPreferredSize(new Dimension(599, 24));
        mbnAgregarActs.setMinimumSize(new Dimension(599, 24));
        mbnAgregarActs.setMaximumSize(new Dimension(599, 24));
        mbnAgregarActs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mbnAgregarActsMousePressed(evt);
            }
        });
        mbnAgregarActs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mbnAgregarActsMouseDragged(evt);
            }
        });

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgAgenda_Virtual/Images/Cerrar.png"))); // NOI18N
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu2MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mbnAgregarActs.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Modificar Actividades");
        jMenu3.setEnabled(false);
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbnAgregarActs.add(jMenu3);

        setJMenuBar(mbnAgregarActs);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    
    
    public void cmbtipact(){
        try{
            DefaultComboBoxModel model = new DefaultComboBoxModel();            
        ResultSet rs = H.Buscar("SELECT nom_tipoact FROM Tipo_Actividades");
        while(rs.next()){
            model.addElement(rs.getString(1));
        }
        cmbtipact.setModel(model);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    public void getAct(){
        try{
        ResultSet rs;
        rs = H.Buscar("SELECT act.nom_act, act.des_act, act.fecha_act, act.hora_act, act.lugar_act, tipact.id_tipoact FROM Actividades AS act, Tipo_Actividades as tipact WHERE act.cod_usu = '"+H.Usuario +"' AND act.nom_act = '"+H.nom_act+"' AND act.id_tipoact = tipact.id_tipoact");
        while(rs.next()){
            txtNomAct.setText(H.desencriptar(rs.getString(1)));
            txtDescripcion.setText(H.desencriptar(rs.getString(2)));
            String fecha = rs.getString(3).substring(0, 10);
            String hora = rs.getString(4).substring(0, 5);
            int dia, mes, año;
            int horas, minutos;
            dia = Integer.parseInt(fecha.substring(8, 10));
            mes = Integer.parseInt(fecha.substring(5, 7));
            año = Integer.parseInt(fecha.substring(0, 4));
            horas = Integer.parseInt(hora.substring(0, 2));
            minutos = Integer.parseInt(hora.substring(3, 5));
            cmbDia.setSelectedIndex(dia -1);
            cmbMes.setSelectedIndex(mes -1);
            if(año == 2014){
            cmbAño.setSelectedIndex(0);
            }
            else{
                cmbAño.setSelectedIndex(1);
            }
            cmbHoras.setSelectedIndex(horas );
            cmbMinutos.setSelectedIndex(minutos );
            txtLugar.setText(H.desencriptar(rs.getString(5)));
            int tipact = rs.getInt(6);
            cmbtipact.setSelectedIndex(tipact - 1);
            
        }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        this.dispose();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu2MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu2MenuKeyPressed

    }//GEN-LAST:event_jMenu2MenuKeyPressed
    
    int pX, pY;
    private void mbnAgregarActsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbnAgregarActsMousePressed
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_mbnAgregarActsMousePressed

    private void mbnAgregarActsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbnAgregarActsMouseDragged
        setLocation(getLocation().x+evt.getX()-pX,getLocation().y+evt.getY()-pY);
    }//GEN-LAST:event_mbnAgregarActsMouseDragged

    private void txtLugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarKeyTyped

    private void txtNomActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomActKeyTyped
        int x = H.SoloLetras(evt);
        if(x == 0){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNomActKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.setAlwaysOnTop(false);
        try {
        ResultSet rs;
        int cod_act = -1, tipact = cmbtipact.getSelectedIndex() + 1 ;
        rs = H.Buscar("SELECT cod_act FROM Actividades WHERE nom_act = '"+H.nom_act+"'");
        
            while(rs.next()){
                    cod_act = rs.getInt(1);                
            }
         
        H.Actualizar("UPDATE Actividades SET nom_act = '"+H.encriptar(txtNomAct.getText())+"', des_act = '"+H.encriptar(txtDescripcion.getText())+"', fecha_act = '"+cmbDia.getSelectedItem().toString() +"/"+cmbMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString()+"', hora_act = '"+cmbHoras.getSelectedItem().toString() +":"+cmbMinutos.getSelectedItem().toString()+"', lugar_act = '"+H.encriptar(txtLugar.getText())+"', id_tipoact = "+tipact+" WHERE cod_act = "+cod_act+"");
        frmActividades.sql = 1;
        this.dispose();
    }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        H.DiasdelMes(cmbDia, cmbMes);
    }//GEN-LAST:event_cmbMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModificarActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModificarActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModificarActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModificarActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmModificarActividades dialog = new frmModificarActividades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbAño;
    private javax.swing.JComboBox cmbDia;
    private javax.swing.JComboBox cmbHoras;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JComboBox cmbMinutos;
    private javax.swing.JComboBox cmbtipact;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JMenuBar mbnAgregarActs;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNomAct;
    // End of variables declaration//GEN-END:variables
}
