/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgAgenda_Virtual;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Carlos
 */
public class frmNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmNotas
     */
    public frmNotas() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)
         this.getUI()).setNorthPane(null);
        this.setLocation(1000, 50);
        txtNota.setComponentPopupMenu(popMnu);
        this.setSize(241,241);
        if(H.cod_nota == -1){
            SaveNote();
        }else{
            GetNote();
        }
        guardarnota.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMnu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        txtNota = new javax.swing.JTextArea();
        mnbNotas = new javax.swing.JMenuBar(){
            public void paintComponent(Graphics g){
                g.drawImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pkgAgenda_Virtual/Images/ToolbarInternal2.png")),0,0,this);
            }
        };
        jMenu1 = new javax.swing.JMenu();
        mnuAgregarTitulo = new javax.swing.JMenuItem();
        TituloNota = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popMnu.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setClosable(true);
        setResizable(true);
        setTitle("Nota");
        setFrameIcon(null);
        setName("Nota"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(null);

        txtNota.setBackground(new java.awt.Color(255, 255, 204));
        txtNota.setColumns(20);
        txtNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNota.setLineWrap(true);
        txtNota.setRows(5);
        txtNota.setToolTipText("Agregue una nota");
        txtNota.setWrapStyleWord(true);
        txtNota.setBorder(null);
        txtNota.setLineWrap(true);
        txtNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNotaMousePressed(evt);
            }
        });
        txtNota.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtNotaMouseDragged(evt);
            }
        });
        getContentPane().add(txtNota);
        txtNota.setBounds(0, 0, 240, 230);

        mnbNotas.setBorder(null);
        mnbNotas.setPreferredSize(new Dimension(this.getWidth(), 25));
        mnbNotas.setMinimumSize(new Dimension(this.getWidth(), 25));
        mnbNotas.setMaximumSize(new Dimension(this.getWidth(), 25));
        mnbNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnbNotasMousePressed(evt);
            }
        });
        mnbNotas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mnbNotasMouseDragged(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgAgenda_Virtual/Images/ToolbarInternal+2.png"))); // NOI18N

        mnuAgregarTitulo.setText("Agregar Titulo");
        mnuAgregarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarTituloActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAgregarTitulo);

        mnbNotas.add(jMenu1);

        TituloNota.setText("Nota");
        TituloNota.setEnabled(false);
        TituloNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnbNotas.add(TituloNota);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgAgenda_Virtual/Images/ToolbarInternalX2.png"))); // NOI18N
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu2MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        mnbNotas.add(Box.createHorizontalGlue());

        mnbNotas.add(jMenu2);

        setJMenuBar(mnbNotas);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void SaveNote(){
        String nom_nota, des_nota;
        cod_nota = H.getMax("SELECT cod_nota FROM Notas");
        posX = this.getX();
        posY = this.getY();
        nom_nota = TituloNota.getText();
        des_nota = txtNota.getText();
        H.Nota("INSERT INTO Notas(cod_nota, nom_nota, des_nota, cod_usu, posX_nota, posY_nota) VALUES("+cod_nota+", '"+nom_nota+"', '"+des_nota+"', "+H.Usuario+", "+posX+", "+posY+")");
    }
    public void GetNote(){
        try{
            rs = H.Buscar("SELECT nom_nota, des_nota, posX_nota, posY_nota FROM Notas WHERE cod_nota = "+H.cod_nota+"");
            rs.next();
            cod_nota = H.cod_nota;
            TituloNota.setText(rs.getString(1));
            txtNota.setText(rs.getString(2));
            this.setLocation(rs.getInt(3), rs.getInt(4));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    Timer guardarnota = new Timer (1000, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           H.Nota("UPDATE Notas SET nom_nota = '"+TituloNota.getText()+"', des_nota = '"+txtNota.getText()+"', posX_nota = "+frmNotas.this.getX()+", posY_nota = "+frmNotas.this.getY()+" WHERE cod_nota = "+cod_nota+"");
     } 
});
    
    ResultSet rs;
    int cod_nota;
    int pX, pY, posX, posY; 
    Helper H = new Helper();
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    txtNota.setSize(this.getWidth()+3, this.getHeight()+3);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
     txtNota.setSize(this.getWidth()+3, this.getHeight()+3);
     
    }//GEN-LAST:event_formMousePressed

    private void txtNotaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotaMouseDragged
    }//GEN-LAST:event_txtNotaMouseDragged
    private void txtNotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotaMousePressed
     
    }//GEN-LAST:event_txtNotaMousePressed
    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        H.Nota("DELETE FROM Notas WHERE cod_nota = "+cod_nota+"");
        this.dispose();
    }//GEN-LAST:event_jMenu2MenuSelected
    private void jMenu2MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu2MenuKeyPressed
        
    }//GEN-LAST:event_jMenu2MenuKeyPressed

    private void mnuAgregarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarTituloActionPerformed
        String esa = JOptionPane.showInputDialog("titulo");
        TituloNota.setText(esa);
    }//GEN-LAST:event_mnuAgregarTituloActionPerformed

    private void mnbNotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbNotasMousePressed
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_mnbNotasMousePressed

    private void mnbNotasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbNotasMouseDragged
        setLocation(getLocation().x+evt.getX()-pX,getLocation().y+evt.getY()-pY);
    }//GEN-LAST:event_mnbNotasMouseDragged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu TituloNota;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mnbNotas;
    private javax.swing.JMenuItem mnuAgregarTitulo;
    private javax.swing.JPopupMenu popMnu;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
}
